name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  JIRA_BASE_URL:  # jira base url https://<yourdomain>.atlassian.net
    description: 'It is the base url'
    required: true
    default: 'World'
  JIRA_USER_EMAIL:  # jira user email human@example.com
    description: 'It is the email to access to jira instance'
    required: true
    default: 'World'
  JIRA_API_TOKEN:  # jira ap token HXe8DGg1iJd2AopzyxkFB7F2
    description: 'Its the token we use to add the comment'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
