name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  JIRA_BASE_URL:  # jira base url https://<yourdomain>.atlassian.net
    description: 'It is the base url'
    required: true
    default: 'World'
  JIRA_USER_EMAIL:  # jira user email human@example.com
    description: 'It is the email to access to jira instance'
    required: true
    default: 'World'
  JIRA_API_TOKEN:  # jira ap token HXe8DGg1iJd2AopzyxkFB7F2
    description: 'Its the token we use to add the comment'
    required: true
    default: 'World'
  event: # This is the even execute the script
    description: 'This is the even execute the script'
    required: true
    default: ${{ github.event_name }}
  idField: # This is the custom field's id 
    description: 'This is the custom field s id'
    required: true
    default: '0000'
  sha: # This is the custom field's id 
    description: 'The commit SHA that triggered the workflow run.'
    required: true
    default: ${{ github.sha }}
  token: # This is the custom field's id 
    description: 'The commit SHA that triggered the workflow run.'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
